### DISCUSSION TITLE
Data table schema - machine translation, languages, translation management systems...

### DISCUSSION THREAD

**Discussion by bittlingmayer** [machinetranslate/machinetranslate.org#232] [General]
We're adding useful lists, for example [a list of TMS with regard to their machine translation integrations](https://github.com/machinetranslate/machinetranslate.org/issues/211).

For this, we should just create data files and do a kind of "join" with a nest loop - see https://jekyllrb.com/docs/datafiles/

We don't want to duplicate data.  So we need to define a proper **schema**.  For example:

`_data/translation-management-systems.yaml`
```
- id: translate5
  name: translate5
  description: ...
  url: https://translate5.net
  cat: true
  machine_translation_integrations:
    - service: deepl
       custom_support: true
       glossary_support: false
       links:
           - https://confluence.translate5.net/display/CON/DeepL

  quality_integrations:
    - service: modelfront
       custom_support: true

  features:
    - name: Edit distance report
       description: ...

  links:
    - /resources/tutorials/translation-management-systems/translate5
 
```

`_data/machine-translation-apis.yaml`
```
- id: google_translate
   name:
     - Google Translate
     - Google Cloud Translation API
     - Google Cloud Translation AutoML
   description:
   url: https://cloud.google.com/translate/
   languages:
   custom_languages:
   glossary_languages: 

- id: deepl
  name: DeepL
  languages:
  custom_languages:
  glossary_languages:
  formality:

- id: modernmt
  name: ModernMT
  ...
  adaptive: true
```

`_data/quality-apis.yaml`
```
- id: modelfront
  name: ModelFront
  description: 
  ...
- id: omniscien
  ...
- id: kantanmt
  ...
```

`_data/languages.yaml`
```
- code: es
   name: Spanish
   locales:
      - code: es-419
         name: Latin American Spanish
      - 
   family: ...
   typology: ...
```
