### ISSUE TITLE
Norwegian: Bokmål and Nynorsk

### ISSUE THREAD

**Issue by ktrnka** [machinetranslate/machinetranslate.org#381]
The Norwegian page only mentions the language code `no` but there's also
- Norwegian Bokmål (`nb`, `nob`), supported by 7 APIs
- Norwegian Nynorsk (`nn`, `nno`), supported by 3 APIs

Those variants don't appear on the language list, nor on the Norwegian page. I'm not sure how we could solve that programmatically so I'm just noting it for now so we don't forget.

--- 

I saw that the Norwegian variants aren't on the Norwegian language page so I'll make a ticket for that too.

_Originally posted by @ktrnka in https://github.com/machinetranslate/machinetranslate.org/issues/377#issuecomment-1370038634_

**Comment by bittlingmayer** [comment]
My guess is that this just requires a change in one of these files:
- [_data/languages.yml](https://github.com/machinetranslate/machinetranslate.org/blob/master/_data/languages.yml)
- [generate.py](https://github.com/machinetranslate/machinetranslate.org/blob/master/generate.py)
- [_data/api-language.yml](https://github.com/machinetranslate/machinetranslate.org/blob/master/_data/api-language.yml)

Depends how we want to deal with it.

**Comment by bittlingmayer** [comment]
languages.yml already lists all codes, so we either need to update generate.py

```
-
  codes: [ 'no', nb, nn, nor, nno, nob ]
  names: [ Norwegian ]
  variant_names: [ Bokmål, Nynorsk, Riksmål, Høgnorsk ]
  family: [ gem, ine ]
  scripts: [ Latn ]
  typology:
    word_order: [ SVO ]
    morphosyntax: [ fusional ]
  territories: [ 'no' ]
```

So I think all we must do is add to https://github.com/machinetranslate/machinetranslate.org/blob/master/_data/api-language.yml under `'*':`
```
  nb: no
  nn: no
```

We should also update `get_language_variant_name` to cover Norwegian and other languages there.
