### ISSUE TITLE
Feature: Link from language family article to parent language family

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#495]
**Problem:** Language family articles do not link the articles of their parent language families.

For example, in an article like https://machinetranslate.org/amharic, we link the immediate and primary language family:

> **Language family**: [Semitic](https://machinetranslate.org/semitic) < [Afro-Asiatic](https://machinetranslate.org/afro-asiatic)

But in the https://machinetranslate.org/semitic article, we do not link to https://machinetranslate.org/afro-asiatic.

**Request:** Add a link to the parent language family.

**Additional context**:

To implement this, we need to add this to https://github.com/machinetranslate/machinetranslate.org/blob/master/_data/language-families.yml

Then we could remove the parent language family from https://github.com/machinetranslate/machinetranslate.org/blob/master/_data/languages.yml

```
-
  codes: [ am, amh ]
  names: [ Amharic ]
  family: [ sem, afa ]
  scripts: [ Ethi ]
  typology:
    word_order: [ SOV ]
    morphosyntax: [  fusional, synthetic ]
  territories: [ et ]
```
Family will change to just
> family: [ sem ]

And add code in generate.py or in the language _layouts/language.html to look this up and add it in the articles.

This will also ensure more consistency.
